###################
# Install Package #
###################

install.packages("shiny")
install.packages("bs4Dash")
install.packages("plotly")
install.packages("DT")
install.packages("shinyWidgets")
install.packages("data.table")
install.packages("readODS")
install.packages("ggplot2")
install.packages("ggdist")
install.packages("psych")
install.packages("tigerstats")
install.packages("lsr")
install.packages("Rmisc")
install.packages("nortest")
install.packages("emmeans")
install.packages("rstatix")
install.packages("afex")
install.packages("gmodels")
install.packages("car")
install.packages("GPArotation")
install.packages("yacca")
install.packages("MASS")
install.packages("candisc")
install.packages("dendextend")
install.packages("irr")
install.packages("ggdendro")
install.packages("distributional")
install.packages("fresh")
install.packages("waiter")
install.packages("datamods")


